x-platform-networks: &platform-networks
  - phenix-platform-network
  - nats_default
  - credo-network
  - kc_default
  - phenix-schema-file-server_default

services:
  geo-location:
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.geolocation
    env_file:
      - ./.env
    networks: *platform-networks

  api-gateway:
    depends_on:
      - geo-location
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.api-gateway
    ports:
      - '5000:5000'
    env_file:
      - ./.env
    networks: *platform-networks

  user:
    depends_on:
      - api-gateway
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.user
    env_file:
      - ./.env
    networks: *platform-networks

  connection:
    depends_on:
      - api-gateway
      - user
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.connection
    env_file:
      - ./.env
    networks: *platform-networks

  issuance:
    depends_on:
      - api-gateway
      - user
      - connection
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.issuance
    env_file:
      - ./.env
    networks: *platform-networks

  ledger:
    depends_on:
      - api-gateway
      - user
      - connection
      - issuance
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.ledger
    env_file:
      - ./.env
    networks: *platform-networks

  organization:
    depends_on:
      - api-gateway
      - user
      - connection
      - issuance
      - ledger
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.organization
    env_file:
      - ./.env
    networks: *platform-networks

  verification:
    depends_on:
      - api-gateway
      - user
      - connection
      - issuance
      - ledger
      - organization
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.verification
    env_file:
      - ./.env
    networks: *platform-networks

  agent-service:
    depends_on:
      - api-gateway
      - user
      - connection
      - issuance
      - ledger
      - organization
      - verification
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.agent-service
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: *platform-networks

  ecosystem:
    depends_on:
      - api-gateway
      - organization
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.ecosystem
    env_file:
      - ./.env
    networks: *platform-networks

  utility:
    depends_on:
      - api-gateway
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.utility
    env_file:
      - ./.env
    networks: *platform-networks

  notification:
    depends_on:
      - api-gateway
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.notification
    env_file:
      - ./.env
    networks: *platform-networks

  webhook:
    depends_on:
      - api-gateway
      - issuance
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.webhook
    env_file:
      - ./.env
    networks: *platform-networks

  marketplace:
    depends_on:
      - api-gateway
      - organization
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.marketplace
    env_file:
      - ./.env
    networks: *platform-networks

  seed:
    profiles:
      - seed
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.seed
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
      POOL_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
      UPDATE_CLIENT_CREDENTIAL_SCRIPT: libs/prisma-service/prisma/scripts/update_client_credential_data.sh
    restart: "no"
    networks: *platform-networks

networks:
  phenix-platform-network:
    external: true
  nats_default:
    external: true
  credo-network:
    external: true
  kc_default:
    external: true
  phenix-schema-file-server_default:
    external: true
