# Stage 1: Build the application
FROM node:18-alpine as build

RUN npm install -g pnpm --ignore-scripts \
    && apk update \
    && apk add openssl \
    && apk add openssh-client \
    && apk add docker \
    && apk add docker-compose 
    
RUN npm install -g pnpm
# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN pnpm i

# Copy the rest of the application code
COPY . .
# RUN cd libs/prisma-service && npx prisma generate
RUN cd libs/prisma-service && npx prisma generate

# Build the user service
RUN pnpm run build agent-service

# Stage 2: Create the final image
FROM node:18-alpine

RUN npm install -g pnpm --ignore-scripts \
    && apk update \
    && apk add openssl \
    && apk add openssh-client \
    && apk add docker \
    && apk add docker-compose 

RUN npm install -g pnpm
# Set the working directory
WORKDIR /app
COPY package.json ./
RUN pnpm install --prod --ignore-scripts \
    && pnpm store prune \
    && rm -rf /root/.local/share/pnpm/store

# Copy the compiled code from the build stage
COPY --from=build /app/dist/apps/agent-service/ ./dist/apps/agent-service/

# Copy the libs folder from the build stage
COPY --from=build /app/libs/ ./libs/
RUN cd libs/prisma-service && npx prisma generate

# Set the command to run the microservice
CMD ["sh", "-c", "cd libs/prisma-service && npx prisma migrate deploy && cd ../.. && node dist/apps/agent-service/main.js"]
